# CMake generated Testfile for 
# Source directory: /session/w683b/tests
# Build directory: /session/w683b/cm/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("agenttime_ut")
subdirs("azure_base32_ut")
subdirs("azure_base64_ut")
subdirs("buffer_ut")
subdirs("constbuffer_array_ut")
subdirs("constbuffer_array_batcher_ut")
subdirs("condition_ut")
subdirs("constbuffer_ut")
subdirs("constmap_ut")
subdirs("crtabstractions_ut")
subdirs("doublylinkedlist_ut")
subdirs("gballoc_ut")
subdirs("gballoc_without_init_ut")
subdirs("hmacsha256_ut")
subdirs("httpapiex_ut")
subdirs("httpapiexsas_ut")
subdirs("httpheaders_ut")
subdirs("httpapicompact_ut")
subdirs("singlylinkedlist_ut")
subdirs("lock_ut")
subdirs("map_ut")
subdirs("refcount_ut")
subdirs("sastoken_ut")
subdirs("connectionstringparser_ut")
subdirs("socketio_berkeley_ut")
subdirs("x509_openssl_ut/engine")
subdirs("x509_openssl_ut/no_engine")
subdirs("string_tokenizer_ut")
subdirs("string_token_ut")
subdirs("strings_ut")
subdirs("tickcounter_ut")
subdirs("tlsio_options_ut")
subdirs("uniqueid_ut")
subdirs("uuid_ut")
subdirs("urlencode_ut")
subdirs("vector_ut")
subdirs("xio_ut")
subdirs("optionhandler_ut")
subdirs("memory_data_ut")
subdirs("uws_client_ut")
subdirs("uws_frame_encoder_ut")
subdirs("wsio_ut")
subdirs("ws_url_ut")
subdirs("tickcounter_freertos_ut")
subdirs("utf8_checker_ut")
subdirs("http_proxy_io_ut")
subdirs("dns_resolver_ut")
subdirs("socket_async_ut")
subdirs("template_ut")
